---
- hosts: "{{target}}"
  become: yes
  gather_facts: no

  tasks:
    - include_role:
        name: deploy
      vars:
        image: redis:6.0
        role_id: redis

    - include_role:
        name: deploy
      vars:
        image: postgres
        role_id: db
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: nextcloud
        volumes:
          - "{{data_dir}}/postgres:/var/lib/postgresql/data"

    - include_role:
        name: deploy
      vars:
        image: nextcloud
        role_id: web
        env:
          POSTGRES_HOST: "{{stack_id}}-db"
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          NEXTCLOUD_HOSTNAME: "{{role_url}}"
        volumes:
          - "{{data_dir}}/nextcloud:/var/www/html"
        labels: |
          "traefik.enable": "true"
          "traefik.http.routers.{{container_id}}.rule": "Host(`{{role_url}}`)"

        

    - include_role:
        name: test
      tags: test
      vars:
        test_item:
          url: "https://{{role_url}}"
          expect_status: 200
          authenticate: true     
