---
- hosts: "{{target}}"
  gather_facts: no
  
  vars:
    - random_salt: "{{ lookup('password', '/dev/null length=10 chars=ascii_letters')}}"

  tasks:
    - name: Ensure main admin user exists
      become: yes
      user:
        name: "{{admin_username}}"
        password: "{{ admin_password | password_hash('sha512', random_salt) }}"
        update_password: on_create
        groups: wheel
        shell: /bin/bash

    - name: Ensure zsh is installed
      become: yes
      apt:
        state: latest
        update-cache: yes
        cache_valid_time: 3600
        package: "zsh"

    - name: Copy zshrc config files
      copy:
        src: ".zshrc"
        dest: /home/{{admin_username}}/.zshrc

    - name: Set shell to zsh
      become: true
      user:
        name: "{{admin_username}}"
        shell: /bin/zsh
   
    - name: Authorize ssh keys for admin user
      authorized_key: 
        user: "{{ admin_username }}"
        key: '{{ item }}'
      with_items: "{{ authorized_keys }}"

    - name: Generate new ssh key pair if not present
      openssh_keypair:
        path: "/home/{{admin_username}}/.ssh/id_rsa"
        owner: "{{admin_username}}"
        force: no

