---
- hosts: "{{target}}"
  become: yes
  gather_facts: no

  tasks:

    - include_role:
        name: deploy
      vars:
        image: postgres
        role_id: db
        env:
          POSTGRES_DB: "{{stack_id}}"
          POSTGRES_USER: "{{stack_id}}"
          POSTGRES_PASSWORD: "{{db_password}}"
        volumes:
          - "{{data_dir}}/postgres:/var/lib/postgresql/data"

    - include_role:
        name: deploy
      vars:
        image: requarks/wiki:2
        role_id: web
        volumes:
          - "{{conf_dir}}/config.yml:/wiki/config.yml"
          - "{{conf_dir}}/id_rsa:/wiki/id_rsa"
          - "{{data_dir}}/wiki:/data"
        labels: |
          "traefik.enable": "true"
          "traefik.http.routers.{{container_id}}.rule": "Host(`{{role_url}}`)"