---
- hosts: "{{target}}"
  become: yes
  gather_facts: no
  
  tasks:
    - include_role:
        name: deploy
      vars:
        image: nicolargo/glances:latest
        role_id: web
        command: "/bin/bash -c 'pip install --upgrade glances && python -m glances -C /glances/conf/glances.conf -w'"
        pid_mode: host
        tty: yes
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - "{{conf_dir}}/glances.conf:/glances/conf/glances.conf:ro"
        labels: |
          "traefik.enable": "true"
          "traefik.http.routers.{{container_id}}.rule": "Host(`{{role_url}}`)"
