---
- hosts: "{{target}}"
  become: yes
  gather_facts: no

  tasks:
    - include_role:
        name: deploy
      vars:
        image: bitwardenrs/server:1.16.1
        role_id: web
        role_subdomain: bitwarden
        env_file: "{{conf_dir}}/settings.env"
        volumes:
          - "{{data_dir}}:/data"
        labels: |
          "traefik.enable": "true"
          "traefik.http.routers.{{container_id}}.rule": "Host(`{{role_url}}`)"

    - include_role:
        name: test
      tags: test
      vars:
        test_item:
          url: "https://{{role_url}}/alive"
          expect_status: 200
          authenticate: true   
