---
- hosts: "{{target}}"
  become: yes
  gather_facts: no

  tasks:
    - include_role:
        name: deploy
      vars:
        image: portainer/portainer:1.24.0
        role_id: web
        command: "--no-auth"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - "{{data_dir}}:/data"
        labels: |
          "traefik.enable": "true"
          "traefik.http.routers.{{container_id}}.rule": "Host(`{{role_url}}`)"

    - include_role:
        name: test
      tags: test
      vars:
        test_item:
          url: "https://portainer.{{domain_name}}"
          expect_status: 200
          authenticate: true



