---
- hosts: "{{target}}"
  become: yes
  gather_facts: no
  

  tasks:
    - include_role:
        name: deploy
      vars:
        image: coderaiser/cloudcmd:latest-alpine
        role_id: web
        volumes:
          - "{{data_dir}}/:/mnt/fs"
        labels: |
          "traefik.enable": "true"
          "traefik.http.routers.{{container_id}}.rule": "Host(`{{role_url}}`)"