---
- hosts: "{{target}}"
  become: yes
  gather_facts: no
  
  vars_files:
      - "secure_vars.yml"

  tasks:
    - name: Install/Update required apt packages
      apt:
        state: latest
        update-cache: yes
        cache_valid_time: 3600
        package: "monit"

    - name: Copy alert utilities
      template:
        src: "{{item}}"
        dest: "/usr/bin/{{item}}"
        mode: "755"
      with_items:
        - "notify"
        - "alert"

    - name: Copy monitrc file
      template:
        src: monitrc
        dest: /etc/monitrc
        mode: "700"

    - name: Check monitrc syntax
      command: "monit -t"
      
    - name: Make sure monit is running
      command: "/usr/bin/monit"

    - name: Reset monit config
      shell: kill -s HUP `cat /var/run/monit.pid`
