---
- hosts: "{{target}}"
  become: yes
  gather_facts: no

  tasks:
    - name: Register job
      vars:
        job_token: "{{host_job_tokens[job_id]}}"
        hour: "*/2"
        minute: "0"
      include_role:
        name: "job"

